# Generated by Django 4.2.11 on 2024-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_organisation_postcode'),
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='users', to='community.organisation', verbose_name='Организации'),
        ),
    ]
