# Generated by Django 4.2.11 on 2024-03-12 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_organisation_postcode'),
        ('users', '0006_user_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь-организация',
                'verbose_name_plural': 'Пользователи-организации',
            },
        ),
        migrations.AddConstraint(
            model_name='userorganisation',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_user_organisation'),
        ),
        migrations.AddConstraint(
            model_name='userorganisation',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('organisation')), _negated=True), name='ban_user_from_organisation'),
        ),
    ]
