# Generated by Django 4.2.11 on 2024-03-12 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_events_options'),
        ('users', '0007_userorganisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.organisation', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='userorganisation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
