# Generated by Django 4.2.11 on 2024-03-11 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='postcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Почтовый индекс должен содержать 6 цифр', regex='^\\d{6}$')], verbose_name='Почтовый индекс'),
        ),
    ]
