# Generated by Django 4.2.11 on 2024-03-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_organisation_postcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('-date',), 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
