# Generated by Django 4.2.11 on 2024-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_events_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.CharField(help_text='Введите полный адрес организации', max_length=255, verbose_name='Адрес организации'),
        ),
    ]
